Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -1,71 +1,36 @@
 name: Upstream Sync
 
-
-
 permissions:
-
-  contents: write
-
-
+  contents: write
 
 on:
-
-  schedule:
-
-    - cron: "0 4 * * *" # At 12PM UTC+8
-
-  workflow_dispatch:
-
-
+  schedule:
+    - cron: "0 4 * * *" # At 12PM UTC+8
+  workflow_dispatch:
 
 jobs:
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
+    runs-on: ubuntu-latest
+    if: ${{ github.event.repository.fork }}
 
-  sync_latest_from_upstream:
+    steps:
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v4
 
-    name: Sync latest commits from upstream repo
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
+        with:
+          upstream_sync_repo: LibreSpark/LibreTV
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
 
-    runs-on: ubuntu-latest
-
-    if: ${{ github.event.repository.fork }}
-
-
-
-    steps:
-
-      # Step 1: run a standard checkout action
-
-      - name: Checkout target repo
-
-        uses: actions/checkout@v4
-
-
-
-      # Step 2: run the sync action
-
-      - name: Sync upstream changes
-
-        id: sync
-
-        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
-
-        with:
-
-          upstream_sync_repo: LibreSpark/LibreTV
-
-          upstream_sync_branch: main
-
-          target_sync_branch: main
-
-          target_repo_token: ${{ secrets.FORK_SYNC_ACTION }}
-
-
-
-      - name: Sync check
-
-        if: failure()
-
-        run: |
-
-          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
-
-          exit 1
+      - name: Sync check
+        if: failure()
+        run: |
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
+          exit 1
